name: test
on:
  push:
    branches: [ feature/add_test ]
  pull_request:
    branches: [ feature/add_test ]
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: testing
        run: go test ./...