name: test
on:
  push:
    branches: [ feature/add_test ]
  pull_request:
    branches: [ feature/add_test ]
jobs:
  golangci:
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          BIND-ADDRESS: 0.0.0.0
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    name: test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: testing
        run: go test ./...