name: QA Checklist Generator

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  generate_qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get PR diff
        id: diff
        run: |
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }} > diff.txt
          DIFF_CONTENT_B64=$(base64 -w 0 diff.txt)
          echo "diff_content_b64=${DIFF_CONTENT_B64}" >> $GITHUB_OUTPUT

      - name: Generate QA checklist using OpenAI API with curl
        id: generate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          DIFF_CONTENT=$(base64 -d <<< "${{ steps.diff.outputs.diff_content_b64 }}")
          
          # プロンプトの構築
          QA_FORMAT="# QA表\n\n| No. | テスト項目 | テスト手順 | 期待結果 | 結果 |\n|-----|------------|----------|------------|----------|\n| 1 | ... | ... | ... | □ OK<br>□ NG |"
          PROMPT="以下はプルリクエストの変更差分です。変更差分の概略を述べて下さい。その後。この差分からQAすべきテスト項目を抽出し、必ず以下のフォーマットに従ってQA表を作成してください。フォーマットを変更せず、内容だけを適切に埋めてください：\n\n${QA_FORMAT}\n\n変更差分:\n${DIFF_CONTENT}"

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "user", "content": "'"$PROMPT"'"}],
              "temperature": 0.3
            }')

          # jqを使ってレスポンスから必要な部分を抽出
          QA_COMMENT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')
          echo "qa_comment<<EOF" >> $GITHUB_OUTPUT
          echo "$QA_COMMENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post QA checklist as PR comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.generate.outputs.qa_comment }}
